"""Repository protocol — shared interface for SQLite and PostgreSQL backends."""

from __future__ import annotations

from typing import Protocol

from ..models import StockMemRecord


class Repository(Protocol):
    async def init(self) -> None: ...
    async def get_id_by_date_symbol(self, record_date: str, symbol: str) -> str | None: ...
    async def upsert(self, record: StockMemRecord) -> str: ...
    async def get(self, record_id: str) -> StockMemRecord | None: ...
    async def get_by_date_symbol(self, record_date: str, symbol: str) -> StockMemRecord | None: ...
    async def list_all(self) -> list[StockMemRecord]: ...
    async def list_missing_returns(self, symbol: str | None = None) -> list[StockMemRecord]: ...
    async def update_future_returns(
        self,
        record_id: str,
        future_return_1d: float | None,
        future_return_7d: float | None,
        future_return_30d: float | None,
    ) -> bool: ...
    async def close(self) -> None: ...
